spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/alumnos/**
          filters:
            - StripPrefix=0
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**
          filters:
            - StripPrefix=0
        - id: exam-service
          uri: lb://exam-service
          predicates:
            - Path=/exams/**
          filters:
            - StripPrefix=0
        - id: answer-service
          uri: lb://answer-service
          predicates:
            - Path=/answers/**
          filters:
            - StripPrefix=0
      globalcors:
        corsConfigurations:
            '[/**]':
                allowedOrigins: ['http://localhost:4200']
                allowedHeaders: ['Content-Type']
                allowedMethods: ['GET','POST','PUT','DELETE']
                 